# Generated by Django 6.0.7 on 2026-07-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("studytime", models.IntegerField()),
                ("failures", models.IntegerField()),
                ("absences", models.IntegerField()),
                ("g1", models.IntegerField()),
                ("g2", models.IntegerField()),
                ("higher", models.CharField(max_length=5)),
                ("prediction", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
